### ISSUE TITLE
Cannot Configure

### ISSUE THREAD

**Issue by AvarianKnight** [will2therich/FlarePanel#10]
Failed to select the database! Check your settings and try again.

I tried changing the configurations, i tried deleting them and using the index.php but neither will work.

Edit: Issue fixed idid something wrong now i'm having the issue with the install with it giving the error " Failed to create user: Field 'psalt' doesn't have a default value"

**Comment by will2therich** [comment]
Hi @AvarianKnight 

What branch are you using?
I suggest using the php7.0 branch the master branch is a tad broken at the momento!

Ta!
